using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CellularAutomata
{
    [Flags]
    public enum FHPParticleState : byte
    {
        None = 0x0, // 0

        RightUp = 0x1, // 1

        Right = 0x2, // 2
        RightUp_Right = RightUp | Right, // 3
        
        RightDown = 0x4, // 4
        RightUp_RightDown = RightUp | RightDown, // 5
        Right_RightDown = Right | RightDown, // 6
        RightUp_Right_RightDown = RightUp | Right | RightDown, // 7

        LeftDown = 0x8, // 8
        RightUp_LeftDown = RightUp | LeftDown, // 9
        Right_LeftDown = Right | LeftDown, // 10
        RightUp_Right_LeftDown = RightUp | Right | LeftDown, // 11
        RightDown_LeftDown = RightDown | LeftDown, // 12
        RightUp_RightDown_LeftDown = RightUp | RightDown | LeftDown, // 13
        Right_RightDown_LeftDown = Right | RightDown | LeftDown, // 14
        RightUp_Right_RightDown_LeftDown = RightUp | Right | RightDown | LeftDown, // 15

        Left = 0x10, // 16
        RightUp_Left = RightUp | Left, // 17
        Right_Left = Right | Left, // 18
        RightUp_Right_Left = RightUp | Right | Left, // 19
        RightDown_Left = RightDown | Left, // 20
        RightUp_RightDown_Left = RightUp | RightDown | Left, // 21
        Right_RightDown_Left = Right | RightDown | Left, // 22
        RightUp_Right_RightDown_Left = RightUp | Right | RightDown | Left, // 23
        LeftDown_Left = LeftDown | Left, // 24
        RightUp_LeftDown_Left = RightUp | LeftDown | Left, // 25
        Right_LeftDown_Left = Right | LeftDown | Left, // 26
        RightUp_Right_LeftDown_Left = RightUp | Right | LeftDown | Left, // 27
        RightDown_LeftDown_Left = RightDown | LeftDown | Left, // 28
        RightUp_RightDown_LeftDown_Left = RightUp | RightDown | LeftDown | Left, // 29
        Right_RightDown_LeftDown_Left = Right | RightDown | LeftDown | Left, // 30
        RightUp_Right_RightDown_LeftDown_Left = RightUp | Right | RightDown | LeftDown | Left, // 31

        LeftUp = 0x20, // 32
        RightUp_LeftUp = RightUp | LeftUp, // 33
        Right_LeftUp = Right | LeftUp, // 34
        RightUp_Right_LeftUp = RightUp | Right | LeftUp, // 35
        RightDown_LeftUp = RightDown | LeftUp, // 36
        RightUp_RightDown_LeftUp = RightUp | RightDown | LeftUp, // 37
        Right_RightDown_LeftUp = Right | RightDown | LeftUp, // 38
        RightUp_Right_RightDown_LeftUp = RightUp | Right | RightDown | LeftUp, // 39
        LeftDown_LeftUp = LeftDown | LeftUp, // 40
        RightUp_LeftDown_LeftUp = RightUp | LeftDown | LeftUp, // 41
        Right_LeftDown_LeftUp = Right | LeftDown | LeftUp, // 42
        RightUp_Right_LeftDown_LeftUp = RightUp | Right | LeftDown | LeftUp, // 43
        RightDown_LeftDown_LeftUp = RightDown | LeftDown | LeftUp, // 44
        RightUp_RightDown_LeftDown_LeftUp = RightUp | RightDown | LeftDown | LeftUp, // 45
        Right_RightDown_LeftDown_LeftUp = Right | RightDown | LeftDown | LeftUp, // 46
        RightUp_Right_RightDown_LeftDown_LeftUp = RightUp | Right | RightDown | LeftDown | LeftUp, // 47
        Left_LeftUp = Left | LeftUp, // 48
        RightUp_Left_LeftUp = RightUp | Left | LeftUp, // 49
        Right_Left_LeftUp = Right | Left, // 50
        RightUp_Right_Left_LeftUp = RightUp | Right | Left | LeftUp, // 51
        RightDown_Left_LeftUp = RightDown | Left | LeftUp, // 52
        RightUp_RightDown_Left_LeftUp = RightUp | RightDown | Left | LeftUp, // 53
        Right_RightDown_Left_LeftUp = Right | RightDown | Left | LeftUp, // 54
        RightUp_Right_RightDown_Left_LeftUp = RightUp | Right | RightDown | Left | LeftUp, // 55
        LeftDown_Left_LeftUp = LeftDown | Left | LeftUp, // 56
        RightUp_LeftDown_Left_LeftUp = RightUp | LeftDown | Left | LeftUp, // 57
        Right_LeftDown_Left_LeftUp = Right | LeftDown | Left | LeftUp, // 58
        RightUp_Right_LeftDown_Left_LeftUp = RightUp | Right | LeftDown | Left | LeftUp, // 59
        RightDown_LeftDown_Left_LeftUp = RightDown | LeftDown | Left | LeftUp, // 60
        RightUp_RightDown_LeftDown_Left_LeftUp = RightUp | RightDown | LeftDown | Left | LeftUp, // 61
        Right_RightDown_LeftDown_Left_LeftUp = Right | RightDown | LeftDown | Left | LeftUp, // 62
        RightUp_Right_RightDown_LeftDown_Left_LeftUp = RightUp | Right | RightDown | LeftDown | Left | LeftUp, // 63

        Rest = 0x40, // 64
        RightUp_Rest = RightUp | Rest, // 65
        Right_Rest = Right | Rest, // 66
        RightUp_Right_Rest = RightUp | Right | Rest, // 67
        RightDown_Rest = RightDown | Rest, // 68
        RightUp_RightDown_Rest = RightUp | RightDown | Rest, // 69
        Right_RightDown_Rest = Right | RightDown | Rest, // 70
        RightUp_Right_RightDown_Rest = RightUp | Right | RightDown | Rest, // 71
        LeftDown_Rest = LeftDown | Rest, // 72
        RightUp_LeftDown_Rest = RightUp | LeftDown | Rest, // 73
        Right_LeftDown_Rest = Right | LeftDown | Rest, // 74
        RightUp_Right_LeftDown_Rest = RightUp | Right | LeftDown | Rest, // 75
        RightDown_LeftDown_Rest = RightDown | LeftDown | Rest, // 76
        RightUp_RightDown_LeftDown_Rest = RightUp | RightDown | LeftDown | Rest, // 77
        Right_RightDown_LeftDown_Rest = Right | RightDown | LeftDown | Rest, // 78
        RightUp_Right_RightDown_LeftDown_Rest = RightUp | Right | RightDown | LeftDown | Rest, // 79
        Left_Rest = Left | Rest, // 80
        RightUp_Left_Rest = RightUp | Left | Rest, // 81
        Right_Left_Rest = Right | Left | Rest, // 82
        RightUp_Right_Left_Rest = RightUp | Right | Left | Rest, // 83
        RightDown_Left_Rest = RightDown | Left | Rest, // 84
        RightUp_RightDown_Left_Rest = RightUp | RightDown | Left | Rest, // 85
        Right_RightDown_Left_Rest = Right | RightDown | Left | Rest, // 86
        RightUp_Right_RightDown_Left_Rest = RightUp | Right | RightDown | Left | Rest, // 87
        LeftDown_Left_Rest = LeftDown | Left | Rest, // 88
        RightUp_LeftDown_Left_Rest = RightUp | LeftDown | Left | Rest, // 89
        Right_LeftDown_Left_Rest = Right | LeftDown | Left | Rest, // 90
        RightUp_Right_LeftDown_Left_Rest = RightUp | Right | LeftDown | Left | Rest, // 91
        RightDown_LeftDown_Left_Rest = RightDown | LeftDown | Left | Rest, // 92
        RightUp_RightDown_LeftDown_Left_Rest = RightUp | RightDown | LeftDown | Left | Rest, // 93
        Right_RightDown_LeftDown_Left_Rest = Right | RightDown | LeftDown | Left | Rest, // 94
        RightUp_Right_RightDown_LeftDown_Left_Rest = RightUp | Right | RightDown | LeftDown | Left | Rest, // 95
        LeftUp_Rest = LeftUp | Rest, // 96
        RightUp_LeftUp_Rest = RightUp | LeftUp | Rest, // 97
        Right_LeftUp_Rest = Right | LeftUp | Rest, // 98
        RightUp_Right_LeftUp_Rest = RightUp | Right | LeftUp | Rest, // 99
        RightDown_LeftUp_Rest = RightDown | LeftUp | Rest, // 100
        RightUp_RightDown_LeftUp_Rest = RightUp | RightDown | LeftUp | Rest, // 101
        Right_RightDown_LeftUp_Rest = Right | RightDown | LeftUp | Rest, // 102
        RightUp_Right_RightDown_LeftUp_Rest = RightUp | Right | RightDown | LeftUp | Rest, // 103
        LeftDown_LeftUp_Rest = LeftDown | LeftUp | Rest, // 104
        RightUp_LeftDown_LeftUp_Rest = RightUp | LeftDown | LeftUp | Rest, // 105
        Right_LeftDown_LeftUp_Rest = Right | LeftDown | LeftUp | Rest, // 106
        RightUp_Right_LeftDown_LeftUp_Rest = RightUp | Right | LeftDown | LeftUp | Rest, // 107
        RightDown_LeftDown_LeftUp_Rest = RightDown | LeftDown | LeftUp | Rest, // 108
        RightUp_RightDown_LeftDown_LeftUp_Rest = RightUp | RightDown | LeftDown | LeftUp | Rest, // 109
        Right_RightDown_LeftDown_LeftUp_Rest = Right | RightDown | LeftDown | LeftUp | Rest, // 110
        RightUp_Right_RightDown_LeftDown_LeftUp_Rest = RightUp | Right | RightDown | LeftDown | LeftUp | Rest, // 111
        Left_LeftUp_Rest = Left | LeftUp | Rest, // 112
        RightUp_Left_LeftUp_Rest = RightUp | Left | LeftUp | Rest, // 113
        Right_Left_LeftUp_Rest = Right | Left | Rest, // 114
        RightUp_Right_Left_LeftUp_Rest = RightUp | Right | Left | LeftUp | Rest, // 115
        RightDown_Left_LeftUp_Rest = RightDown | Left | LeftUp | Rest, // 116
        RightUp_RightDown_Left_LeftUp_Rest = RightUp | RightDown | Left | LeftUp | Rest, // 117
        Right_RightDown_Left_LeftUp_Rest = Right | RightDown | Left | LeftUp | Rest, // 118
        RightUp_Right_RightDown_Left_LeftUp_Rest = RightUp | Right | RightDown | Left | LeftUp | Rest, // 119
        LeftDown_Left_LeftUp_Rest = LeftDown | Left | LeftUp | Rest, // 120
        RightUp_LeftDown_Left_LeftUp_Rest = RightUp | LeftDown | Left | LeftUp | Rest, // 121
        Right_LeftDown_Left_LeftUp_Rest = Right | LeftDown | Left | LeftUp | Rest, // 122
        RightUp_Right_LeftDown_Left_LeftUp_Rest = RightUp | Right | LeftDown | Left | LeftUp | Rest, // 123
        RightDown_LeftDown_Left_LeftUp_Rest = RightDown | LeftDown | Left | LeftUp | Rest, // 124
        RightUp_RightDown_LeftDown_Left_LeftUp_Rest = RightUp | RightDown | LeftDown | Left | LeftUp | Rest, // 125
        Right_RightDown_LeftDown_Left_LeftUp_Rest = Right | RightDown | LeftDown | Left | LeftUp | Rest, // 126
        RightUp_Right_RightDown_LeftDown_Left_LeftUp_Rest = RightUp | Right | RightDown | LeftDown | Left | LeftUp | Rest, // 127

        Wall = 0x80, // 128
        RightUp_Wall = RightUp | Wall, // 129
        Right_Wall = Right | Wall, // 130
        RightUp_Right_Wall = RightUp | Right | Wall, // 131
        RightDown_Wall = RightDown | Wall, // 132
        RightUp_RightDown_Wall = RightUp | RightDown | Wall, // 133
        Right_RightDown_Wall = Right | RightDown | Wall, // 134
        RightUp_Right_RightDown_Wall = RightUp | Right | RightDown | Wall, // 135
        LeftDown_Wall = LeftDown | Wall, // 136
        RightUp_LeftDown_Wall = RightUp | LeftDown | Wall, // 137
        Right_LeftDown_Wall = Right | LeftDown | Wall, // 138
        RightUp_Right_LeftDown_Wall = RightUp | Right | LeftDown | Wall, // 139
        RightDown_LeftDown_Wall = RightDown | LeftDown | Wall, // 140
        RightUp_RightDown_LeftDown_Wall = RightUp | RightDown | LeftDown | Wall, // 141
        Right_RightDown_LeftDown_Wall = Right | RightDown | LeftDown | Wall, // 142
        RightUp_Right_RightDown_LeftDown_Wall = RightUp | Right | RightDown | LeftDown | Wall, // 143
        Left_Wall = Left | Wall, // 144
        RightUp_Left_Wall = RightUp | Left | Wall, // 145
        Right_Left_Wall = Right | Left | Wall, // 146
        RightUp_Right_Left_Wall = RightUp | Right | Left | Wall, // 147
        RightDown_Left_Wall = RightDown | Left | Wall, // 148
        RightUp_RightDown_Left_Wall = RightUp | RightDown | Left | Wall, // 149
        Right_RightDown_Left_Wall = Right | RightDown | Left | Wall, // 150
        RightUp_Right_RightDown_Left_Wall = RightUp | Right | RightDown | Left | Wall, // 151
        LeftDown_Left_Wall = LeftDown | Left | Wall, // 152
        RightUp_LeftDown_Left_Wall = RightUp | LeftDown | Left | Wall, // 153
        Right_LeftDown_Left_Wall = Right | LeftDown | Left | Wall, // 154
        RightUp_Right_LeftDown_Left_Wall = RightUp | Right | LeftDown | Left | Wall, // 155
        RightDown_LeftDown_Left_Wall = RightDown | LeftDown | Left | Wall, // 156
        RightUp_RightDown_LeftDown_Left_Wall = RightUp | RightDown | LeftDown | Left | Wall, // 157
        Right_RightDown_LeftDown_Left_Wall = Right | RightDown | LeftDown | Left | Wall, // 158
        RightUp_Right_RightDown_LeftDown_Left_Wall = RightUp | Right | RightDown | LeftDown | Left | Wall, // 159
        LeftUp_Wall = LeftUp | Wall, // 160
        RightUp_LeftUp_Wall = RightUp | LeftUp | Wall, // 161
        Right_LeftUp_Wall = Right | LeftUp | Wall, // 162
        RightUp_Right_LeftUp_Wall = RightUp | Right | LeftUp | Wall, // 163
        RightDown_LeftUp_Wall = RightDown | LeftUp | Wall, // 164
        RightUp_RightDown_LeftUp_Wall = RightUp | RightDown | LeftUp | Wall, // 165
        Right_RightDown_LeftUp_Wall = Right | RightDown | LeftUp | Wall, // 166
        RightUp_Right_RightDown_LeftUp_Wall = RightUp | Right | RightDown | LeftUp | Wall, // 167
        LeftDown_LeftUp_Wall = LeftDown | LeftUp | Wall, // 168
        RightUp_LeftDown_LeftUp_Wall = RightUp | LeftDown | LeftUp | Wall, // 169
        Right_LeftDown_LeftUp_Wall = Right | LeftDown | LeftUp | Wall, // 170
        RightUp_Right_LeftDown_LeftUp_Wall = RightUp | Right | LeftDown | LeftUp | Wall, // 171
        RightDown_LeftDown_LeftUp_Wall = RightDown | LeftDown | LeftUp | Wall, // 172
        RightUp_RightDown_LeftDown_LeftUp_Wall = RightUp | RightDown | LeftDown | LeftUp | Wall, // 173
        Right_RightDown_LeftDown_LeftUp_Wall = Right | RightDown | LeftDown | LeftUp | Wall, // 174
        RightUp_Right_RightDown_LeftDown_LeftUp_Wall = RightUp | Right | RightDown | LeftDown | LeftUp | Wall, // 175
        Left_LeftUp_Wall = Left | LeftUp | Wall, // 176
        RightUp_Left_LeftUp_Wall = RightUp | Left | LeftUp | Wall, // 177
        Right_Left_LeftUp_Wall = Right | Left | Wall, // 178
        RightUp_Right_Left_LeftUp_Wall = RightUp | Right | Left | LeftUp | Wall, // 179
        RightDown_Left_LeftUp_Wall = RightDown | Left | LeftUp | Wall, // 180
        RightUp_RightDown_Left_LeftUp_Wall = RightUp | RightDown | Left | LeftUp | Wall, // 181
        Right_RightDown_Left_LeftUp_Wall = Right | RightDown | Left | LeftUp | Wall, // 182
        RightUp_Right_RightDown_Left_LeftUp_Wall = RightUp | Right | RightDown | Left | LeftUp | Wall, // 183
        LeftDown_Left_LeftUp_Wall = LeftDown | Left | LeftUp | Wall, // 184
        RightUp_LeftDown_Left_LeftUp_Wall = RightUp | LeftDown | Left | LeftUp | Wall, // 185
        Right_LeftDown_Left_LeftUp_Wall = Right | LeftDown | Left | LeftUp | Wall, // 186
        RightUp_Right_LeftDown_Left_LeftUp_Wall = RightUp | Right | LeftDown | Left | LeftUp | Wall, // 187
        RightDown_LeftDown_Left_LeftUp_Wall = RightDown | LeftDown | Left | LeftUp | Wall, // 188
        RightUp_RightDown_LeftDown_Left_LeftUp_Wall = RightUp | RightDown | LeftDown | Left | LeftUp | Wall, // 189
        Right_RightDown_LeftDown_Left_LeftUp_Wall = Right | RightDown | LeftDown | Left | LeftUp | Wall, // 190
        RightUp_Right_RightDown_LeftDown_Left_LeftUp_Wall = RightUp | Right | RightDown | LeftDown | Left | Wall, // 191
        Rest_Wall = Rest | Wall, // 192
        RightUp_Rest_Wall = RightUp | Rest | Wall, // 193
        Right_Rest_Wall = Right | Rest | Wall, // 194
        RightUp_Right_Rest_Wall = RightUp | Right | Rest | Wall, // 195
        RightDown_Rest_Wall = RightDown | Rest | Wall, // 196
        RightUp_RightDown_Rest_Wall = RightUp | RightDown | Rest | Wall, // 197
        Right_RightDown_Rest_Wall = Right | RightDown | Rest | Wall, // 198
        RightUp_Right_RightDown_Rest_Wall = RightUp | Right | RightDown | Rest | Wall, // 199
        LeftDown_Rest_Wall = LeftDown | Rest | Wall, // 200
        RightUp_LeftDown_Rest_Wall = RightUp | LeftDown | Rest | Wall, // 201
        Right_LeftDown_Rest_Wall = Right | LeftDown | Rest | Wall, // 202
        RightUp_Right_LeftDown_Rest_Wall = RightUp | Right | LeftDown | Rest | Wall, // 203
        RightDown_LeftDown_Rest_Wall = RightDown | LeftDown | Rest | Wall, // 204
        RightUp_RightDown_LeftDown_Rest_Wall = RightUp | RightDown | LeftDown | Rest | Wall, // 205
        Right_RightDown_LeftDown_Rest_Wall = Right | RightDown | LeftDown | Rest | Wall, // 206
        RightUp_Right_RightDown_LeftDown_Rest_Wall = RightUp | Right | RightDown | LeftDown | Rest | Wall, // 207
        Left_Rest_Wall = Left | Rest | Wall, // 208
        RightUp_Left_Rest_Wall = RightUp | Left | Rest | Wall, // 209
        Right_Left_Rest_Wall = Right | Left | Rest | Wall, // 210
        RightUp_Right_Left_Rest_Wall = RightUp | Right | Left | Rest | Wall, // 211
        RightDown_Left_Rest_Wall = RightDown | Left | Rest | Wall, // 212
        RightUp_RightDown_Left_Rest_Wall = RightUp | RightDown | Left | Rest | Wall, // 213
        Right_RightDown_Left_Rest_Wall = Right | RightDown | Left | Rest | Wall, // 214
        RightUp_Right_RightDown_Left_Rest_Wall = RightUp | Right | RightDown | Left | Rest | Wall, // 215
        LeftDown_Left_Rest_Wall = LeftDown | Left | Rest | Wall, // 216
        RightUp_LeftDown_Left_Rest_Wall = RightUp | LeftDown | Left | Rest | Wall, // 217
        Right_LeftDown_Left_Rest_Wall = Right | LeftDown | Left | Rest | Wall, // 218
        RightUp_Right_LeftDown_Left_Rest_Wall = RightUp | Right | LeftDown | Left | Rest | Wall, // 219
        RightDown_LeftDown_Left_Rest_Wall = RightDown | LeftDown | Left | Rest | Wall, // 220
        RightUp_RightDown_LeftDown_Left_Rest_Wall = RightUp | RightDown | LeftDown | Left | Rest | Wall, // 221
        Right_RightDown_LeftDown_Left_Rest_Wall = Right | RightDown | LeftDown | Left | Rest | Wall, // 222
        RightUp_Right_RightDown_LeftDown_Left_Rest_Wall = RightUp | Right | RightDown | LeftDown | Left | Rest | Wall, // 223
        LeftUp_Rest_Wall = LeftUp | Rest | Wall, // 224
        RightUp_LeftUp_Rest_Wall = RightUp | LeftUp | Rest | Wall, // 225
        Right_LeftUp_Rest_Wall = Right | LeftUp | Rest | Wall, // 226
        RightUp_Right_LeftUp_Rest_Wall = RightUp | Right | LeftUp | Rest | Wall, // 227
        RightDown_LeftUp_Rest_Wall = RightDown | LeftUp | Rest | Wall, // 228
        RightUp_RightDown_LeftUp_Rest_Wall = RightUp | RightDown | LeftUp | Rest | Wall, // 229
        Right_RightDown_LeftUp_Rest_Wall = Right | RightDown | LeftUp | Rest | Wall, // 230
        RightUp_Right_RightDown_LeftUp_Rest_Wall = RightUp | Right | RightDown | LeftUp | Rest | Wall, // 231
        LeftDown_LeftUp_Rest_Wall = LeftDown | LeftUp | Rest | Wall, // 232
        RightUp_LeftDown_LeftUp_Rest_Wall = RightUp | LeftDown | LeftUp | Rest| Wall, // 233
        Right_LeftDown_LeftUp_Rest_Wall = Right | LeftDown | LeftUp | Rest | Wall, // 234
        RightUp_Right_LeftDown_LeftUp_Rest_Wall = RightUp | Right | LeftDown | LeftUp | Rest | Wall, // 235
        RightDown_LeftDown_LeftUp_Rest_Wall = RightDown | LeftDown | LeftUp | Rest | Wall, // 236
        RightUp_RightDown_LeftDown_LeftUp_Rest_Wall = RightUp | RightDown | LeftDown | LeftUp | Rest | Wall, // 237
        Right_RightDown_LeftDown_LeftUp_Rest_Wall = Right | RightDown | LeftDown | LeftUp | Rest | Wall, // 238
        RightUp_Right_RightDown_LeftDown_LeftUp_Rest_Wall = RightUp | Right | RightDown | LeftDown | LeftUp | Rest | Wall, // 239
        Left_LeftUp_Rest_Wall = Left | LeftUp | Rest | Wall, // 240
        RightUp_Left_LeftUp_Rest_Wall = RightUp | Left | LeftUp | Rest | Wall, // 241
        Right_Left_LeftUp_Rest_Wall = Right | Left | Rest | Wall, // 242
        RightUp_Right_Left_LeftUp_Rest_Wall = RightUp | Right | Left | LeftUp | Rest | Wall, // 243
        RightDown_Left_LeftUp_Rest_Wall = RightDown | Left | LeftUp | Rest | Wall, // 244
        RightUp_RightDown_Left_LeftUp_Rest_Wall = RightUp | RightDown | Left | LeftUp | Rest | Wall, // 245
        Right_RightDown_Left_LeftUp_Rest_Wall = Right | RightDown | Left | LeftUp | Rest | Wall, // 246
        RightUp_Right_RightDown_Left_LeftUp_Rest_Wall = RightUp | Right | RightDown | Left | LeftUp | Rest | Wall, // 247
        LeftDown_Left_LeftUp_Rest_Wall = LeftDown | Left | LeftUp | Rest | Wall, // 248
        RightUp_LeftDown_Left_LeftUp_Rest_Wall = RightUp | LeftDown | Left | LeftUp | Rest | Wall, // 249
        Right_LeftDown_Left_LeftUp_Rest_Wall = Right | LeftDown | Left | LeftUp | Rest | Wall, // 250
        RightUp_Right_LeftDown_Left_LeftUp_Rest_Wall = RightUp | Right | LeftDown | Left | LeftUp | Rest | Wall, // 251
        RightDown_LeftDown_Left_LeftUp_Rest_Wall = RightDown | LeftDown | Left | LeftUp | Rest | Wall, // 252
        RightUp_RightDown_LeftDown_Left_LeftUp_Rest_Wall = RightUp | RightDown | LeftDown | Left | LeftUp | Rest | Wall, // 253
        Right_RightDown_LeftDown_Left_LeftUp_Rest_Wall = Right | RightDown | LeftDown | Left | LeftUp | Rest | Wall, // 254
        RightUp_Right_RightDown_LeftDown_Left_LeftUp_Rest_Wall = RightUp | Right | RightDown | LeftDown | Left | LeftUp | Rest | Wall, // 255
    }
}
