using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CellularAutomata
{
    [Flags]
    enum FHPParticleState : byte
    {
        None = 0x0, // 0

        NE = 0x1, // 1

        E = 0x2, // 2
        NE_E = NE | E, // 3

        SE = 0x4, // 4
        NE_SE = NE | SE, // 5
        E_SE = E | SE, // 6
        NE_E_SE = NE | E | SE, // 7

        SW = 0x8, // 8
        NE_SW = NE | SW, // 9
        E_SW = E | SW, // 10
        NE_E_SW = NE | E | SW, // 11
        SE_SW = SE | SW, // 12
        NE_SE_SW = NE | SE | SW, // 13
        E_SE_SW = E | SE | SW, // 14
        NE_E_SE_SW = NE | E | SE | SW, // 15

        W = 0x10, // 16
        NE_W = NE | W, // 17
        E_W = E | W, // 18
        NE_E_W = NE | E | W, // 19
        SE_W = SE | W, // 20
        NE_SE_W = NE | SE | W, // 21
        E_SE_W = E | SE | W, // 22
        NE_E_SE_W = NE | E | SE | W, // 23
        SW_W = SW | W, // 24
        NE_SW_W = NE | SW | W, // 25
        E_SW_W = E | SW | W, // 26
        NE_E_SW_W = NE | E | SW | W, // 27
        SE_SW_W = SE | SW | W, // 28
        NE_SE_SW_W = NE | SE | SW | W, // 29
        E_SE_SW_W = E | SE | SW | W, // 30
        NE_E_SE_SW_W = NE | E | SE | SW | W, // 31

        NW = 0x20, // 32
        NE_NW = NE | NW, // 33
        E_NW = E | NW, // 34
        NE_E_NW = NE | E | NW, // 35
        SE_NW = SE | NW, // 36
        NE_SE_NW = NE | SE | NW, // 37
        E_SE_NW = E | SE | NW, // 38
        NE_E_SE_NW = NE | E | SE | NW, // 39
        SW_NW = SW | NW, // 40
        NE_SW_NW = NE | SW | NW, // 41
        E_SW_NW = E | SW | NW, // 42
        NE_E_SW_NW = NE | E | SW | NW, // 43
        SE_SW_NW = SE | SW | NW, // 44
        NE_SE_SW_NW = NE | SE | SW | NW, // 45
        E_SE_SW_NW = E | SE | SW | NW, // 46
        NE_E_SE_SW_NW = NE | E | SE | SW | NW, // 47
        W_NW = W | NW, // 48
        NE_W_NW = NE | W | NW, // 49
        E_W_NW = E | W, // 50
        NE_E_W_NW = NE | E | W | NW, // 51
        SE_W_NW = SE | W | NW, // 52
        NE_SE_W_NW = NE | SE | W | NW, // 53
        E_SE_W_NW = E | SE | W | NW, // 54
        NE_E_SE_W_NW = NE | E | SE | W | NW, // 55
        SW_W_NW = SW | W | NW, // 56
        NE_SW_W_NW = NE | SW | W | NW, // 57
        E_SW_W_NW = E | SW | W | NW, // 58
        NE_E_SW_W_NW = NE | E | SW | W | NW, // 59
        SE_SW_W_NW = SE | SW | W | NW, // 60
        NE_SE_SW_W_NW = NE | SE | SW | W | NW, // 61
        E_SE_SW_W_NW = E | SE | SW | W | NW, // 62
        NE_E_SE_SW_W_NW = NE | E | SE | SW | W | NW, // 63

        Rest = 0x40, // 64
        NE_Rest = NE | Rest, // 65
        E_Rest = E | Rest, // 66
        NE_E_Rest = NE | E | Rest, // 67
        SE_Rest = SE | Rest, // 68
        NE_SE_Rest = NE | SE | Rest, // 69
        E_SE_Rest = E | SE | Rest, // 70
        NE_E_SE_Rest = NE | E | SE | Rest, // 71
        SW_Rest = SW | Rest, // 72
        NE_SW_Rest = NE | SW | Rest, // 73
        E_SW_Rest = E | SW | Rest, // 74
        NE_E_SW_Rest = NE | E | SW | Rest, // 75
        SE_SW_Rest = SE | SW | Rest, // 76
        NE_SE_SW_Rest = NE | SE | SW | Rest, // 77
        E_SE_SW_Rest = E | SE | SW | Rest, // 78
        NE_E_SE_SW_Rest = NE | E | SE | SW | Rest, // 79
        W_Rest = W | Rest, // 80
        NE_W_Rest = NE | W | Rest, // 81
        E_W_Rest = E | W | Rest, // 82
        NE_E_W_Rest = NE | E | W | Rest, // 83
        SE_W_Rest = SE | W | Rest, // 84
        NE_SE_W_Rest = NE | SE | W | Rest, // 85
        E_SE_W_Rest = E | SE | W | Rest, // 86
        NE_E_SE_W_Rest = NE | E | SE | W | Rest, // 87
        SW_W_Rest = SW | W | Rest, // 88
        NE_SW_W_Rest = NE | SW | W | Rest, // 89
        E_SW_W_Rest = E | SW | W | Rest, // 90
        NE_E_SW_W_Rest = NE | E | SW | W | Rest, // 91
        SE_SW_W_Rest = SE | SW | W | Rest, // 92
        NE_SE_SW_W_Rest = NE | SE | SW | W | Rest, // 93
        E_SE_SW_W_Rest = E | SE | SW | W | Rest, // 94
        NE_E_SE_SW_W_Rest = NE | E | SE | SW | W | Rest, // 95
        NW_Rest = NW | Rest, // 96
        NE_NW_Rest = NE | NW | Rest, // 97
        E_NW_Rest = E | NW | Rest, // 98
        NE_E_NW_Rest = NE | E | NW | Rest, // 99
        SE_NW_Rest = SE | NW | Rest, // 100
        NE_SE_NW_Rest = NE | SE | NW | Rest, // 101
        E_SE_NW_Rest = E | SE | NW | Rest, // 102
        NE_E_SE_NW_Rest = NE | E | SE | NW | Rest, // 103
        SW_NW_Rest = SW | NW | Rest, // 104
        NE_SW_NW_Rest = NE | SW | NW | Rest, // 105
        E_SW_NW_Rest = E | SW | NW | Rest, // 106
        NE_E_SW_NW_Rest = NE | E | SW | NW | Rest, // 107
        SE_SW_NW_Rest = SE | SW | NW | Rest, // 108
        NE_SE_SW_NW_Rest = NE | SE | SW | NW | Rest, // 109
        E_SE_SW_NW_Rest = E | SE | SW | NW | Rest, // 110
        NE_E_SE_SW_NW_Rest = NE | E | SE | SW | NW | Rest, // 111
        W_NW_Rest = W | NW | Rest, // 112
        NE_W_NW_Rest = NE | W | NW | Rest, // 113
        E_W_NW_Rest = E | W | Rest, // 114
        NE_E_W_NW_Rest = NE | E | W | NW | Rest, // 115
        SE_W_NW_Rest = SE | W | NW | Rest, // 116
        NE_SE_W_NW_Rest = NE | SE | W | NW | Rest, // 117
        E_SE_W_NW_Rest = E | SE | W | NW | Rest, // 118
        NE_E_SE_W_NW_Rest = NE | E | SE | W | NW | Rest, // 119
        SW_W_NW_Rest = SW | W | NW | Rest, // 120
        NE_SW_W_NW_Rest = NE | SW | W | NW | Rest, // 121
        E_SW_W_NW_Rest = E | SW | W | NW | Rest, // 122
        NE_E_SW_W_NW_Rest = NE | E | SW | W | NW | Rest, // 123
        SE_SW_W_NW_Rest = SE | SW | W | NW | Rest, // 124
        NE_SE_SW_W_NW_Rest = NE | SE | SW | W | NW | Rest, // 125
        E_SE_SW_W_NW_Rest = E | SE | SW | W | NW | Rest, // 126
        NE_E_SE_SW_W_NW_Rest = NE | E | SE | SW | W | NW | Rest, // 127

        Wall = 0x80, // 128
        NE_Wall = NE | Wall, // 129
        E_Wall = E | Wall, // 130
        NE_E_Wall = NE | E | Wall, // 131
        SE_Wall = SE | Wall, // 132
        NE_SE_Wall = NE | SE | Wall, // 133
        E_SE_Wall = E | SE | Wall, // 134
        NE_E_SE_Wall = NE | E | SE | Wall, // 135
        SW_Wall = SW | Wall, // 136
        NE_SW_Wall = NE | SW | Wall, // 137
        E_SW_Wall = E | SW | Wall, // 138
        NE_E_SW_Wall = NE | E | SW | Wall, // 139
        SE_SW_Wall = SE | SW | Wall, // 140
        NE_SE_SW_Wall = NE | SE | SW | Wall, // 141
        E_SE_SW_Wall = E | SE | SW | Wall, // 142
        NE_E_SE_SW_Wall = NE | E | SE | SW | Wall, // 143
        W_Wall = W | Wall, // 144
        NE_W_Wall = NE | W | Wall, // 145
        E_W_Wall = E | W | Wall, // 146
        NE_E_W_Wall = NE | E | W | Wall, // 147
        SE_W_Wall = SE | W | Wall, // 148
        NE_SE_W_Wall = NE | SE | W | Wall, // 149
        E_SE_W_Wall = E | SE | W | Wall, // 150
        NE_E_SE_W_Wall = NE | E | SE | W | Wall, // 151
        SW_W_Wall = SW | W | Wall, // 152
        NE_SW_W_Wall = NE | SW | W | Wall, // 153
        E_SW_W_Wall = E | SW | W | Wall, // 154
        NE_E_SW_W_Wall = NE | E | SW | W | Wall, // 155
        SE_SW_W_Wall = SE | SW | W | Wall, // 156
        NE_SE_SW_W_Wall = NE | SE | SW | W | Wall, // 157
        E_SE_SW_W_Wall = E | SE | SW | W | Wall, // 158
        NE_E_SE_SW_W_Wall = NE | E | SE | SW | W | Wall, // 159
        NW_Wall = NW | Wall, // 160
        NE_NW_Wall = NE | NW | Wall, // 161
        E_NW_Wall = E | NW | Wall, // 162
        NE_E_NW_Wall = NE | E | NW | Wall, // 163
        SE_NW_Wall = SE | NW | Wall, // 164
        NE_SE_NW_Wall = NE | SE | NW | Wall, // 165
        E_SE_NW_Wall = E | SE | NW | Wall, // 166
        NE_E_SE_NW_Wall = NE | E | SE | NW | Wall, // 167
        SW_NW_Wall = SW | NW | Wall, // 168
        NE_SW_NW_Wall = NE | SW | NW | Wall, // 169
        E_SW_NW_Wall = E | SW | NW | Wall, // 170
        NE_E_SW_NW_Wall = NE | E | SW | NW | Wall, // 171
        SE_SW_NW_Wall = SE | SW | NW | Wall, // 172
        NE_SE_SW_NW_Wall = NE | SE | SW | NW | Wall, // 173
        E_SE_SW_NW_Wall = E | SE | SW | NW | Wall, // 174
        NE_E_SE_SW_NW_Wall = NE | E | SE | SW | NW | Wall, // 175
        W_NW_Wall = W | NW | Wall, // 176
        NE_W_NW_Wall = NE | W | NW | Wall, // 177
        E_W_NW_Wall = E | W | Wall, // 178
        NE_E_W_NW_Wall = NE | E | W | NW | Wall, // 179
        SE_W_NW_Wall = SE | W | NW | Wall, // 180
        NE_SE_W_NW_Wall = NE | SE | W | NW | Wall, // 181
        E_SE_W_NW_Wall = E | SE | W | NW | Wall, // 182
        NE_E_SE_W_NW_Wall = NE | E | SE | W | NW | Wall, // 183
        SW_W_NW_Wall = SW | W | NW | Wall, // 184
        NE_SW_W_NW_Wall = NE | SW | W | NW | Wall, // 185
        E_SW_W_NW_Wall = E | SW | W | NW | Wall, // 186
        NE_E_SW_W_NW_Wall = NE | E | SW | W | NW | Wall, // 187
        SE_SW_W_NW_Wall = SE | SW | W | NW | Wall, // 188
        NE_SE_SW_W_NW_Wall = NE | SE | SW | W | NW | Wall, // 189
        E_SE_SW_W_NW_Wall = E | SE | SW | W | NW | Wall, // 190
        NE_E_SE_SW_W_NW_Wall = NE | E | SE | SW | W | Wall, // 191
        Rest_Wall = Rest | Wall, // 192
        NE_Rest_Wall = NE | Rest | Wall, // 193
        E_Rest_Wall = E | Rest | Wall, // 194
        NE_E_Rest_Wall = NE | E | Rest | Wall, // 195
        SE_Rest_Wall = SE | Rest | Wall, // 196
        NE_SE_Rest_Wall = NE | SE | Rest | Wall, // 197
        E_SE_Rest_Wall = E | SE | Rest | Wall, // 198
        NE_E_SE_Rest_Wall = NE | E | SE | Rest | Wall, // 199
        SW_Rest_Wall = SW | Rest | Wall, // 200
        NE_SW_Rest_Wall = NE | SW | Rest | Wall, // 201
        E_SW_Rest_Wall = E | SW | Rest | Wall, // 202
        NE_E_SW_Rest_Wall = NE | E | SW | Rest | Wall, // 203
        SE_SW_Rest_Wall = SE | SW | Rest | Wall, // 204
        NE_SE_SW_Rest_Wall = NE | SE | SW | Rest | Wall, // 205
        E_SE_SW_Rest_Wall = E | SE | SW | Rest | Wall, // 206
        NE_E_SE_SW_Rest_Wall = NE | E | SE | SW | Rest | Wall, // 207
        W_Rest_Wall = W | Rest | Wall, // 208
        NE_W_Rest_Wall = NE | W | Rest | Wall, // 209
        E_W_Rest_Wall = E | W | Rest | Wall, // 210
        NE_E_W_Rest_Wall = NE | E | W | Rest | Wall, // 211
        SE_W_Rest_Wall = SE | W | Rest | Wall, // 212
        NE_SE_W_Rest_Wall = NE | SE | W | Rest | Wall, // 213
        E_SE_W_Rest_Wall = E | SE | W | Rest | Wall, // 214
        NE_E_SE_W_Rest_Wall = NE | E | SE | W | Rest | Wall, // 215
        SW_W_Rest_Wall = SW | W | Rest | Wall, // 216
        NE_SW_W_Rest_Wall = NE | SW | W | Rest | Wall, // 217
        E_SW_W_Rest_Wall = E | SW | W | Rest | Wall, // 218
        NE_E_SW_W_Rest_Wall = NE | E | SW | W | Rest | Wall, // 219
        SE_SW_W_Rest_Wall = SE | SW | W | Rest | Wall, // 220
        NE_SE_SW_W_Rest_Wall = NE | SE | SW | W | Rest | Wall, // 221
        E_SE_SW_W_Rest_Wall = E | SE | SW | W | Rest | Wall, // 222
        NE_E_SE_SW_W_Rest_Wall = NE | E | SE | SW | W | Rest | Wall, // 223
        NW_Rest_Wall = NW | Rest | Wall, // 224
        NE_NW_Rest_Wall = NE | NW | Rest | Wall, // 225
        E_NW_Rest_Wall = E | NW | Rest | Wall, // 226
        NE_E_NW_Rest_Wall = NE | E | NW | Rest | Wall, // 227
        SE_NW_Rest_Wall = SE | NW | Rest | Wall, // 228
        NE_SE_NW_Rest_Wall = NE | SE | NW | Rest | Wall, // 229
        E_SE_NW_Rest_Wall = E | SE | NW | Rest | Wall, // 230
        NE_E_SE_NW_Rest_Wall = NE | E | SE | NW | Rest | Wall, // 231
        SW_NW_Rest_Wall = SW | NW | Rest | Wall, // 232
        NE_SW_NW_Rest_Wall = NE | SW | NW | Rest| Wall, // 233
        E_SW_NW_Rest_Wall = E | SW | NW | Rest | Wall, // 234
        NE_E_SW_NW_Rest_Wall = NE | E | SW | NW | Rest | Wall, // 235
        SE_SW_NW_Rest_Wall = SE | SW | NW | Rest | Wall, // 236
        NE_SE_SW_NW_Rest_Wall = NE | SE | SW | NW | Rest | Wall, // 237
        E_SE_SW_NW_Rest_Wall = E | SE | SW | NW | Rest | Wall, // 238
        NE_E_SE_SW_NW_Rest_Wall = NE | E | SE | SW | NW | Rest | Wall, // 239
        W_NW_Rest_Wall = W | NW | Rest | Wall, // 240
        NE_W_NW_Rest_Wall = NE | W | NW | Rest | Wall, // 241
        E_W_NW_Rest_Wall = E | W | Rest | Wall, // 242
        NE_E_W_NW_Rest_Wall = NE | E | W | NW | Rest | Wall, // 243
        SE_W_NW_Rest_Wall = SE | W | NW | Rest | Wall, // 244
        NE_SE_W_NW_Rest_Wall = NE | SE | W | NW | Rest | Wall, // 245
        E_SE_W_NW_Rest_Wall = E | SE | W | NW | Rest | Wall, // 246
        NE_E_SE_W_NW_Rest_Wall = NE | E | SE | W | NW | Rest | Wall, // 247
        SW_W_NW_Rest_Wall = SW | W | NW | Rest | Wall, // 248
        NE_SW_W_NW_Rest_Wall = NE | SW | W | NW | Rest | Wall, // 249
        E_SW_W_NW_Rest_Wall = E | SW | W | NW | Rest | Wall, // 250
        NE_E_SW_W_NW_Rest_Wall = NE | E | SW | W | NW | Rest | Wall, // 251
        SE_SW_W_NW_Rest_Wall = SE | SW | W | NW | Rest | Wall, // 252
        NE_SE_SW_W_NW_Rest_Wall = NE | SE | SW | W | NW | Rest | Wall, // 253
        E_SE_SW_W_NW_Rest_Wall = E | SE | SW | W | NW | Rest | Wall, // 254
        NE_E_SE_SW_W_NW_Rest_Wall = NE | E | SE | SW | W | NW | Rest | Wall, // 255
    }
}
